# The URL the site will be built for
# base_url = "https://endsoflines.com"
base_url = "https://serif-7.github.io"

# The site title and description; used in feeds by default.
title = "Ends of Lines"
description = "Serif's Blog"

# The site theme to use.
# theme = ""

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

output_dir = "docs"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
